### PR TITLE
Remove memcached restart from update command.

### PR DESCRIPTION
**Pull request by lewiscollard**
I introduced this in 013efab. For reasons unknown, on Ubuntu, `service memcached restart` (and `/etc/init.d/memcached restart`) end up killing memcached most (but not all) of the time, and never starting again.

I don't see a better option than removing it; having to restart memcached manually every time an update requires it is less manual work than having to manually start it nearly all the time after an update.

### CODE REVIEW

**Comment by danielsamuels** [comment]
Would `service memcached stop && service memcached start` work, or perhaps `service memcached reload`?

**Comment by lewiscollard** [comment]
Nope. Doing a `stop` and a `start` also kills memcached. This has happened on two different servers so far.

**Comment by danielsamuels** [comment]
I've been putting some thought into this, I think managing memcached in supervisor might be the best option. We're reloading it for the application anyway, so we can probably just do a memcached one in there too. This config should work:

```
[program:memcached]
command=/usr/bin/memcached -p 11211 -u memcache -m 64 -c 1024 -t 4
autostart=true
autorestart=true
user=root
priority=100
redirect_stderr=true
stdout_logfile=/var/log/memcached.log
```

**Comment by lewiscollard** [comment]
That is a very good idea.

**Pull request closed without merging**
