### PR TITLE
Remove Ansible, add HTTP/2 & Let's Encrypt

### LINKED ISSUE #4: Add ability to setup HTTPS on domains

### LINKED ISSUE #23: Enable HTTP/2 in nginx conf
Requires a newer version of nginx, not sure if it's available via apt-get.

http://caniuse.com/#feat=http2
https://www.nginx.com/blog/nginx-1-9-5/

### LINKED ISSUE #38: Use the latest version of nginx

### LINKED ISSUE #43: Fails to install Node / NVM on deployment
When deploying NW Brown Portal it errored: https://gist.github.com/dan-gamble/1ccb6ee11ab9db7dbdfdee3b549e6169

Then update gave this:

```bash
[139.59.172.113] sudo: chmod -R g+w /var/www/nwbrown*
[139.59.172.113] sudo: . ~/.nvm/nvm.sh && yarn
[139.59.172.113] out: /bin/bash: /home/nwbrown/.nvm/nvm.sh: No such file or directory
[139.59.172.113] out:
```

### LINKED ISSUE #44: Make `deploy` work on Debian Jessie (current stable)
If nothing else, it gives us options if Ubuntu ever does something terrible, and supporting one extra Debian variant makes it easier to support others.

`deploy` almost worked perfectly, with these tweaks:

* Install `aptitude` manually (it is by default on Ubuntu, but not Debian - needs to be done before any other packages are installed)
* Install `ufw` (it's not by default on Debian)
* Make it install postgresql 9.4 rather than 9.3 if deploying to Jessie, as Jessie doesn't have 9.3.
* `pg_tune` does not exist in jessie, so skip this step in case of a Jessie system (and so the 'Backuping PostgreSQL main config file' task should not be run either)
* `dpkg-reconfigure` locales takes a very long time and I suspect it's actually being run interactively (it's non-interactive on Ubuntu) - see https://serverfault.com/questions/362903/how-do-you-set-a-locale-non-interactively-on-debian-ubuntu
* A `sudo systemctl daemon-reload` is necessary to get postgresql to start (a `service postgresql restart` might be necessary after that). I don't know why.
* Debian's SSH is a bit more finicky; it won't allow SSH connections if someone's home directory is writable. 750 on the home directory and 700 on everything, recursively, on `.ssh` fixes this.

### LINKED ISSUE #46: If no changes were pulled, exit immediately
Thinking about the situation where two Circle builds are running in parallel, often the changes from the 2nd build are pulled in the first build.  It's probably worth making the update script immediately exit if the `git pull` doesn't pull anything - otherwise it's going to go through the `yarn run build`, `supervisorctl restart all` etc when nothing will change.  This would make duplicate builds finish a lot quicker.

### PR DESCRIPTION
**Pull request by danielsamuels**
* Resolves #38 
* Resolves #23 
* Resolves #43 
* Resolves #44 
* Resolves #4
* Resolves #46 

---

This is quite a large change.  I've stripped Ansible out to allow us to be freed from the shackles it's been placing on us. With this PR we gain the following:

* Ability to deploy to Ubuntu 16.04
* Ability to deploy to Debian Jessie (in theory, not tested)
* Default installation uses HTTP/2
* Default installation uses SSL via Let's Encrypt - scores A on SSLLabs (not currently sure what's preventing an A+)
* Uses Nginx and Let's Encrypt PPAs to allow for...
* Default installation uses the latest available version of Nginx
* Default installation uses the latest available version of Postgres
* Default installation uses the latest available version of OpenSSL
* Fixes an issue with NVM / Yarn etc not installing properly
* Gives us the ability to use Python 3 in our projects

Other changes which aren't necessarily additions:

* Deployment keys are generated for the project user, rather than the deploy user. This removes the requirement for `chmod` and `chown` everywhere.  All project files are downloaded, installed etc through the project user.  The deploy user is now only used for logging in.
* Slightly improved progress output, success / failure states are inline
* Adds the ability to deploy without any user input (pass `--noinput`)
* Provides a debug flag to improve debugging of problems (pass `--debug`)
* Requires production settings to be used which avoids issues with domain specifications
* Requires SSL to be installed
* Removes the support for very old server.json files which only allowed for a single host
* Swappiness and cache pressure values have been tweaked to be more suited for servers
* Ensures the static folder exists within the project before running `collectstatic`

I would like to investigate having per-OS commands, but this might be best as a separate PR

TODO:

* [x] I need to finish off removing Ansible completely, there might still be some remnants in other management files, I need to check.
* [x] I would like to clean up some of the imports, mainly getting rid of `from fabric.api import *`
* [x] Update the README, it still refers to Ansible
* [x] Implement the initial user fix (from #45)
* [x] Add a command to add production domains to SSL certs
* [x] Update the `update` command to support the new user structure.

### CODE REVIEW

**Comment by dan-gamble** [comment]
I'm not really sure how to review this so i'll wait until the other have then 👍  it

**Comment by dan-gamble** [comment]
```
================================================== Standard output ==================================================

Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
The provided email for a registration was invalid :: Unable to update registration :: DNS problem: SERVFAIL looking up MX for onespacemedia.com
Please see the logfiles in /var/log/letsencrypt for more details.

======================================================================================================================
```

Getting this on `Run certbot`

**Comment by danielsamuels** [comment]
Add this to the nginx config: 

```
    # Make TCP send multiple buffers as individual packets.                                                                                   
    tcp_nodelay on;

    # Send half empty (or half full) packets.                                                                                                 
    tcp_nopush  on;
```

Taken from https://news.ycombinator.com/item?id=14617879

**Comment by dan-gamble** [comment]
Will these last commits break if using `python3.6` as that needs the PPA?

**Comment by lewiscollard** [comment]
@dan-gamble The 3.6 PPA needs to be added in `deploy` (guarded by a test for `3.6`) - this is among my todos.

**Pull request merged**
